// sidebarsCommunity.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsCommunity = {
  community: [
    {
      type:'category',
      label:'反國會濫權｜線上培力課程',
      collapsed:true,
      items:[
            {
      type: 'autogenerated',
      dirName: 'course',
    }
    ]
    },{
      type:'category',
      label:'反國會濫權｜第二階段行動',
      collapsed:true,
      items:[
            {
      type: 'autogenerated',
      dirName: 'archive',
    }
    ]
    }
  , {
    type:'category',
    label:'反國會濫權｜重返立院集結行動',
    collapsed:false,
    items:[
          {
    type: 'autogenerated',
    dirName: 'archive2',
  }
  ]
  }
  ],
};

export default sidebarsCommunity;
