// sidebarsCommunity.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsCommunity = {
  community: [
    {
      type:'category',
      label:'反國會濫權｜線上培力課程',
      collapsed:false,
      items:[
            {
      type: 'autogenerated',
      dirName: 'course',
    }
    ]
    }
,
  ],
};

export default sidebarsCommunity;
